SELECT RIGHT(REPEAT('0', 4) || WRSTORE, 4)
     , B.STCTRY
  FROM MRIRCW1P A,
       TBLSTR   B
 WHERE WRSKU = 999999999 
   AND WRBLOCK = 'H' 
   AND A.WRSTORE = B.STRNUM
   AND A.WRACTION = 'D'
   AND B.STPOLL = 'Y'
  WITH UR
